 //0,0,244,2223
 //
 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("BVE Cornwall ATS Plugin")]
[assembly: AssemblyDescription("BVE Cornwall ATS Plugin for OpenBVE")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Christopher Lees")]
[assembly: AssemblyProduct("BVEC_ATS")]
[assembly: AssemblyCopyright("BSD 2-Clause Licence")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyFileVersion("0.0.244.893")]